import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function AttendanceHistory() {
  const [items, setItems] = useState([]), [status, setStatus] = useState('all'), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); const { data, error } = await supabase.from('learner_records').select('id,event_date,attendance_status,title,student:profiles!learner_records_student_id_fkey(full_name,admission_number,class_level,class_stream)').eq('kind', 'attendance').order('event_date', { ascending: false }).limit(500); if (error) setError(workflowError(error)); else setItems(data || []); setLoading(false) }, [])
  useEffect(() => { load() }, [load])
  const shown = useMemo(() => items.filter(item => status === 'all' || item.attendance_status === status), [items, status])
  function download() { const rows = [['Date', 'Learner', 'Admission number', 'Class', 'Stream', 'Status'], ...shown.map(item => [item.event_date, item.student?.full_name || '', item.student?.admission_number || '', item.student?.class_level || '', item.student?.class_stream || '', item.attendance_status])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = 'fordridge-attendance-history.csv'; link.click(); URL.revokeObjectURL(url) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Class register</p><h1>Attendance history</h1><p className="progress-report-note">Review attendance recorded by your account. Administrators can review school-wide records.</p></div><button onClick={download} disabled={!shown.length}>Export CSV</button></header>{error && <p className="workflow-error" role="alert">{error}</p>}<section className="workflow-panel"><label>Attendance status<select value={status} onChange={event => setStatus(event.target.value)}><option value="all">All statuses</option>{['present', 'late', 'absent', 'excused'].map(item => <option key={item}>{item}</option>)}</select></label><div className="workflow-scroll"><table className="workflow-table"><thead><tr><th>Date</th><th>Learner</th><th>Class</th><th>Status</th></tr></thead><tbody>{shown.map(item => <tr key={item.id}><td>{item.event_date}</td><td>{item.student?.full_name || 'Learner'}<small>{item.student?.admission_number || ''}</small></td><td>{[item.student?.class_level, item.student?.class_stream].filter(Boolean).join(' · ') || 'Not recorded'}</td><td>{item.attendance_status}</td></tr>)}</tbody></table>{loading ? <p role="status">Loading attendance history…</p> : !shown.length && <p className="portal-empty-copy">No matching attendance records found.</p>}</div></section></section>
}
