import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function BulkMarks({ profile }) {
  const admin = profile.role === 'admin'; const [learners, setLearners] = useState([]), [groups, setGroups] = useState([]), [group, setGroup] = useState(''), [marks, setMarks] = useState({}), [error, setError] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false); const [form, setForm] = useState({ title: '', event_date: new Date().toLocaleDateString('en-CA'), academic_year: String(new Date().getFullYear()), academic_term: 'Term 1', max_score: '100' })
  const load = useCallback(async () => { let students = supabase.from('profiles').select('id,full_name,class_level,class_stream,campus_id').eq('role', 'student').neq('enrollment_status', 'inactive').order('full_name'); if (!admin) students = students.eq('campus_id', profile.campus_id); const { data, error } = await students; if (error) { setError(workflowError(error)); return } let available = [...new Set((data || []).filter(item => item.class_level).map(item => `${item.class_level}||${item.class_stream || ''}`))]; if (!admin) { const assignments = await supabase.from('teacher_class_assignments').select('class_level,class_stream').eq('teacher_id', profile.id); if (assignments.error) { setError(workflowError(assignments.error)); return } const allowed = new Set((assignments.data || []).map(item => `${item.class_level}||${item.class_stream || ''}`)); available = available.filter(item => allowed.has(item)) } setLearners(data || []); setGroups(available); setGroup(current => current || available[0] || '') }, [admin, profile.campus_id, profile.id])
  useEffect(() => { load() }, [load])
  const [level, stream] = group.split('||')
  const selected = learners.filter(item => item.class_level === level && (item.class_stream || '') === stream)
  useEffect(() => {
    setMarks(Object.fromEntries(selected.map(item => [item.id, ''])))
  }, [group])
  async function save(event) { event.preventDefault(); if (!form.title.trim()) return setError('Enter an assessment title.'); if (selected.some(item => marks[item.id] === '')) return setError('Enter a mark for every learner.'); setSaving(true); setError(''); const { error } = await supabase.rpc('record_bulk_marks', { p_title: form.title.trim(), p_event_date: form.event_date, p_academic_year: Number(form.academic_year), p_academic_term: form.academic_term, p_max_score: Number(form.max_score), p_entries: selected.map(item => ({ student_id: item.id, score: Number(marks[item.id]) })) }); if (error) setError(workflowError(error)); else setNotice(`Marks saved for ${selected.length} learners.`); setSaving(false) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Assessment register</p><h1>Bulk mark entry</h1><p className="progress-report-note">Enter one assessment for a whole assigned class.</p></div></header>{error && <p className="workflow-error" role="alert">{error}</p>}{notice && <p className="workflow-notice" role="status">{notice}</p>}<form className="workflow-panel" onSubmit={save}><div className="bulk-marks-controls"><label>Class<select value={group} onChange={e => setGroup(e.target.value)}>{groups.map(item => <option key={item} value={item}>{item.replace('||', ' · ')}</option>)}</select></label><label>Assessment title<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Date<input type="date" required value={form.event_date} onChange={e => setForm({ ...form, event_date: e.target.value })} /></label><label>Year<input type="number" min="2000" required value={form.academic_year} onChange={e => setForm({ ...form, academic_year: e.target.value })} /></label><label>Term<select value={form.academic_term} onChange={e => setForm({ ...form, academic_term: e.target.value })}>{['Term 1', 'Term 2', 'Term 3'].map(item => <option key={item}>{item}</option>)}</select></label><label>Out of<input type="number" min="0.01" required value={form.max_score} onChange={e => setForm({ ...form, max_score: e.target.value })} /></label></div>{selected.length ? <><div className="bulk-marks-list">{selected.map(item => <label key={item.id}><span>{item.full_name}</span><input type="number" min="0" max={form.max_score} step="0.01" required value={marks[item.id] || ''} onChange={e => setMarks({ ...marks, [item.id]: e.target.value })} /></label>)}</div><button className="primary-action" disabled={saving}>{saving ? 'Saving…' : 'Save class marks'}</button></> : <p className="portal-empty-copy">No assigned class with active learners is available.</p>}</form></section>
}
