import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

const columns = ['full_name', 'phone', 'admission_number', 'class_level', 'class_stream']
export default function BulkLearnerImport() {
  const [campuses, setCampuses] = useState([]), [campus, setCampus] = useState(''), [password, setPassword] = useState(''), [rows, setRows] = useState([]), [results, setResults] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { supabase.from('campuses').select('id,name').order('name').then(({ data, error }) => { if (error) setError(workflowError(error)); else { setCampuses(data || []); setCampus(data?.[0]?.id || '') } }) }, [])
  function readFile(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const lines = String(reader.result).trim().split(/\r?\n/).filter(Boolean); const headers = lines.shift()?.split(',').map(value => value.trim()); if (columns.some((column, index) => headers?.[index] !== column)) { setError(`CSV must start with: ${columns.join(', ')}`); setRows([]); return } setError(''); setRows(lines.map((line, index) => { const values = line.split(',').map(value => value.trim()); return { line: index + 2, full_name: values[0], phone: values[1], admission_number: values[2], class_level: values[3], class_stream: values[4] } }).filter(row => row.full_name || row.phone)) }; reader.readAsText(file) }
  async function importRows() { if (!campus || password.length < 12 || !rows.length) return; setBusy(true); setResults([]); const outcome = []; for (const row of rows) { const { data, error } = await supabase.functions.invoke('create-portal-account', { body: { ...row, role: 'student', campus_id: campus, password, enrollment_status: 'active' } }); outcome.push({ ...row, success: !error && !data?.error, message: data?.error || error?.message || 'Created' }) } setResults(outcome); setBusy(false) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Learner management</p><h1>Bulk learner import</h1><p className="progress-report-note">Upload a CSV to provision learner portal accounts. Do not include commas inside any field.</p></div></header>{error && <p className="workflow-error" role="alert">{error}</p>}<section className="workflow-panel"><p><strong>Required CSV columns:</strong> <code>{columns.join(', ')}</code></p><label>CSV file<input type="file" accept=".csv,text/csv" onChange={readFile} /></label><label>Campus<select value={campus} onChange={e => setCampus(e.target.value)}>{campuses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Shared initial password (minimum 12 characters)<input type="password" minLength="12" value={password} onChange={e => setPassword(e.target.value)} /></label>{rows.length > 0 && <><p>{rows.length} learner{rows.length === 1 ? '' : 's'} ready to import.</p><button className="primary-action" disabled={busy || password.length < 12} onClick={importRows}>{busy ? 'Creating accounts…' : 'Create learner accounts'}</button></>}</section>{results.length > 0 && <section className="workflow-panel"><h2>Import results</h2>{results.map(row => <p key={row.line}>{row.success ? '✓' : '×'} {row.full_name || `Line ${row.line}`} — {row.message}</p>)}</section>}</section>
}
