import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function ClassAssignments({ profile }) {
  const admin = profile.role === 'admin'; const [items, setItems] = useState([]); const [teachers, setTeachers] = useState([]); const [campuses, setCampuses] = useState([]); const [draft, setDraft] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const [assignments, staff, schools] = await Promise.all([supabase.from('teacher_class_assignments').select('id,class_level,class_stream,subject,teacher:profiles!teacher_class_assignments_teacher_id_fkey(full_name),campus:campuses(name)').order('class_level'), admin ? supabase.from('profiles').select('id,full_name,campus_id').eq('role', 'teacher').order('full_name') : Promise.resolve({ data: [], error: null }), admin ? supabase.from('campuses').select('id,name').order('name') : Promise.resolve({ data: [], error: null })]); const failed = [assignments, staff, schools].find(item => item.error); if (failed) setError(workflowError(failed.error)); else { setItems(assignments.data || []); setTeachers(staff.data || []); setCampuses(schools.data || []) } }, [admin])
  useEffect(() => { load() }, [load])
  async function save(event) { event.preventDefault(); setSaving(true); const { error } = await supabase.from('teacher_class_assignments').insert({ teacher_id: draft.teacher_id, campus_id: draft.campus_id, class_level: draft.class_level.trim(), class_stream: draft.class_stream.trim() || null, subject: draft.subject.trim() || null }); if (error) setError(workflowError(error)); else { setDraft(null); await load() } setSaving(false) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Teaching workspace</p><h1>Class assignments</h1><p className="progress-report-note">Assignments determine which class registers teachers can use.</p></div>{admin && <button className="primary-action" onClick={() => setDraft({ teacher_id: '', campus_id: '', class_level: '', class_stream: '', subject: '' })}>+ Assign class</button>}</header>{error && <p className="workflow-error" role="alert">{error}</p>}{draft && <form className="workflow-panel workflow-form" onSubmit={save}><label>Teacher<select required value={draft.teacher_id} onChange={e => setDraft({ ...draft, teacher_id: e.target.value })}><option value="">Select teacher</option>{teachers.map(item => <option value={item.id} key={item.id}>{item.full_name}</option>)}</select></label><label>Campus<select required value={draft.campus_id} onChange={e => setDraft({ ...draft, campus_id: e.target.value })}><option value="">Select campus</option>{campuses.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Class / form<input required value={draft.class_level} onChange={e => setDraft({ ...draft, class_level: e.target.value })} /></label><label>Stream<input value={draft.class_stream} onChange={e => setDraft({ ...draft, class_stream: e.target.value })} /></label><label>Subject (optional)<input value={draft.subject} onChange={e => setDraft({ ...draft, subject: e.target.value })} /></label><div className="workflow-actions"><button className="primary-action" disabled={saving}>{saving ? 'Saving…' : 'Save assignment'}</button><button type="button" onClick={() => setDraft(null)}>Cancel</button></div></form>}<section className="workflow-panel"><div className="workflow-scroll"><table className="workflow-table"><thead><tr><th>Teacher</th><th>Campus</th><th>Class</th><th>Subject</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.teacher?.full_name}</td><td>{item.campus?.name}</td><td>{item.class_level}{item.class_stream ? ` · ${item.class_stream}` : ''}</td><td>{item.subject || 'Class register'}</td></tr>)}</tbody></table>{!items.length && <p className="portal-empty-copy">No class assignments have been created yet.</p>}</div></section></section>
}
