import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function ExpenseCashbook() {
  const [items, setItems] = useState([]), [draft, setDraft] = useState(null), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const { data, error } = await supabase.from('cashbook_expenses').select('*').order('expense_date', { ascending: false }).limit(250); if (error) setError(workflowError(error)); else setItems(data || []) }, [])
  useEffect(() => { load() }, [load])
  const total = useMemo(() => items.filter(item => item.currency === 'USD').reduce((sum, item) => sum + Number(item.amount || 0), 0), [items])
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); const { error } = await supabase.from('cashbook_expenses').insert({ expense_date: draft.expense_date, category: draft.category.trim(), description: draft.description.trim(), amount: Number(draft.amount), currency: draft.currency, reference: draft.reference.trim() || null }); if (error) setError(workflowError(error)); else { setDraft(null); await load() } setSaving(false) }
  return <section className="expense-cashbook"><header className="workflow-heading"><div><p className="eyebrow">Finance management</p><h1>Expense cashbook</h1><p className="progress-report-note">Record school outgoings separately from learner fee collections.</p></div><button className="primary-action" onClick={() => setDraft({ expense_date: new Date().toLocaleDateString('en-CA'), category: '', description: '', amount: '', currency: 'USD', reference: '' })}>+ Record expense</button></header>{error && <p className="workflow-error" role="alert">{error}</p>}<section className="portal-summary-grid"><article><span>Recorded expenses</span><strong>{items.length}</strong><small>Latest 250 cashbook entries</small></article><article><span>Total outgoings</span><strong>US${total.toFixed(2)}</strong><small>Based on currently visible USD entries</small></article></section>{draft && <form className="workflow-panel workflow-form" onSubmit={save}><label>Date<input required type="date" value={draft.expense_date} onChange={e => setDraft({ ...draft, expense_date: e.target.value })} /></label><label>Category<input required value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })} placeholder="e.g. Transport" /></label><label>Amount<input required min="0.01" step="0.01" type="number" value={draft.amount} onChange={e => setDraft({ ...draft, amount: e.target.value })} /></label><label>Currency<select value={draft.currency} onChange={e => setDraft({ ...draft, currency: e.target.value })}><option>USD</option><option>ZiG</option></select></label><label className="workflow-wide">Description<textarea required value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} /></label><label>Reference (optional)<input value={draft.reference} onChange={e => setDraft({ ...draft, reference: e.target.value })} /></label><div className="workflow-actions"><button className="primary-action" disabled={saving}>{saving ? 'Saving…' : 'Save expense'}</button><button type="button" onClick={() => setDraft(null)}>Cancel</button></div></form>}<section className="workflow-panel"><div className="workflow-scroll"><table className="workflow-table"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td>{item.expense_date}</td><td>{item.category}</td><td>{item.description}</td><td>{item.reference || '—'}</td><td>{item.currency} {Number(item.amount).toFixed(2)}</td></tr>)}</tbody></table>{!items.length && <p className="portal-empty-copy">No expenses have been recorded yet.</p>}</div></section></section>
}
