import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function GradeBands() {
  const [campuses, setCampuses] = useState([]), [bands, setBands] = useState([]), [draft, setDraft] = useState({ campus_id: '', minimum_percent: '', maximum_percent: '', grade: '', descriptor: '' }), [error, setError] = useState('')
  const load = useCallback(async () => { const [schools, grades] = await Promise.all([supabase.from('campuses').select('id,name').order('name'), supabase.from('report_grade_bands').select('*,campus:campuses(name)').order('minimum_percent', { ascending: false })]); const failed = [schools, grades].find(item => item.error); if (failed) setError(workflowError(failed.error)); else { setCampuses(schools.data || []); setBands(grades.data || []); setDraft(current => ({ ...current, campus_id: current.campus_id || schools.data?.[0]?.id || '' })) } }, [])
  useEffect(() => { load() }, [load])
  async function save(event) { event.preventDefault(); setError(''); const { error } = await supabase.from('report_grade_bands').insert({ ...draft, minimum_percent: Number(draft.minimum_percent), maximum_percent: Number(draft.maximum_percent), grade: draft.grade.trim(), descriptor: draft.descriptor.trim() || null }); if (error) setError(workflowError(error)); else { setDraft({ campus_id: draft.campus_id, minimum_percent: '', maximum_percent: '', grade: '', descriptor: '' }); load() } }
  async function remove(id) { const { error } = await supabase.from('report_grade_bands').delete().eq('id', id); if (error) setError(workflowError(error)); else load() }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Formal reports</p><h1>Grade bands</h1><p className="progress-report-note">Create the official Fordridge percentage-to-grade ranges used on report cards.</p></div></header>{error && <p className="workflow-error" role="alert">{error}</p>}<form className="workflow-panel workflow-form" onSubmit={save}><label>Campus<select required value={draft.campus_id} onChange={e => setDraft({ ...draft, campus_id: e.target.value })}>{campuses.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Minimum percentage<input type="number" min="0" max="100" step="0.01" required value={draft.minimum_percent} onChange={e => setDraft({ ...draft, minimum_percent: e.target.value })} /></label><label>Maximum percentage<input type="number" min="0" max="100" step="0.01" required value={draft.maximum_percent} onChange={e => setDraft({ ...draft, maximum_percent: e.target.value })} /></label><label>Grade<input required value={draft.grade} onChange={e => setDraft({ ...draft, grade: e.target.value })} placeholder="[EDIT THIS]" /></label><label>Descriptor<input value={draft.descriptor} onChange={e => setDraft({ ...draft, descriptor: e.target.value })} placeholder="[EDIT THIS]" /></label><div className="workflow-actions"><button className="primary-action">Add grade band</button></div></form><section className="workflow-panel"><div className="workflow-scroll"><table className="workflow-table"><thead><tr><th>Campus</th><th>Range</th><th>Grade</th><th>Descriptor</th><th /></tr></thead><tbody>{bands.map(band => <tr key={band.id}><td>{band.campus?.name}</td><td>{band.minimum_percent}%–{band.maximum_percent}%</td><td>{band.grade}</td><td>{band.descriptor || '—'}</td><td><button onClick={() => remove(band.id)}>Remove</button></td></tr>)}</tbody></table>{!bands.length && <p className="portal-empty-copy">No grade bands are configured yet.</p>}</div></section></section>
}
