import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function LearningAnalytics() {
  const [records, setRecords] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true)
  const load = useCallback(async () => { const { data, error } = await supabase.from('learner_records').select('kind,title,score,max_score,attendance_status,event_date').in('kind', ['academic', 'attendance']).order('event_date', { ascending: false }).limit(1000); if (error) setError(workflowError(error)); else setRecords(data || []); setLoading(false) }, [])
  useEffect(() => { load() }, [load])
  const data = useMemo(() => { const academic = records.filter(item => item.kind === 'academic' && item.score !== null); const attendance = records.filter(item => item.kind === 'attendance'); const subjects = Object.values(academic.reduce((result, item) => { const key = item.title || 'Untitled subject'; const percent = Number(item.score) / Number(item.max_score) * 100; const current = result[key] || { title: key, total: 0, count: 0 }; result[key] = { ...current, total: current.total + percent, count: current.count + 1 }; return result }, {})).map(item => ({ ...item, average: item.total / item.count })).sort((a, b) => b.average - a.average); const present = attendance.filter(item => ['present', 'late'].includes(item.attendance_status)).length; return { academic, attendance, subjects, average: academic.length ? academic.reduce((sum, item) => sum + Number(item.score) / Number(item.max_score) * 100, 0) / academic.length : null, attendanceRate: attendance.length ? present / attendance.length * 100 : null } }, [records])
  return <section><header className="workflow-heading"><div><p className="eyebrow">Learning insights</p><h1>Academic analytics</h1><p className="progress-report-note">A live summary of records currently available to your account.</p></div><button onClick={load}>Refresh</button></header>{error && <p className="workflow-error" role="alert">{error}</p>}{loading ? <p role="status">Loading analytics…</p> : <><section className="portal-summary-grid"><article><span>Academic entries</span><strong>{data.academic.length}</strong><small>Recorded assessments</small></article><article><span>Average mark</span><strong>{data.average === null ? '—' : `${data.average.toFixed(1)}%`}</strong><small>Across available academic entries</small></article><article><span>Attendance</span><strong>{data.attendanceRate === null ? '—' : `${data.attendanceRate.toFixed(1)}%`}</strong><small>Present or late records</small></article></section><section className="workflow-panel"><div className="portal-section-heading"><div><p className="eyebrow">Performance by subject</p><h2>Recorded averages</h2></div></div>{data.subjects.length ? <div className="analytics-bars">{data.subjects.map(item => <article key={item.title}><div><strong>{item.title}</strong><span>{item.average.toFixed(1)}% · {item.count} record{item.count === 1 ? '' : 's'}</span></div><i><b style={{ width: `${Math.min(100, item.average)}%` }} /></i></article>)}</div> : <p className="portal-empty-copy">No academic records are available yet.</p>}</section></>}</section>
}
