import { useCallback, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function NotificationCenter({ user }) {
  const [notices, setNotices] = useState([]), [readIds, setReadIds] = useState(new Set()), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); const [announcements, reads] = await Promise.all([supabase.from('announcements').select('id,title,body,published_at').order('published_at', { ascending: false }).limit(40), supabase.from('announcement_reads').select('announcement_id').eq('user_id', user.id)]); const failed = [announcements, reads].find(item => item.error); if (failed) setError(workflowError(failed.error)); else { setNotices(announcements.data || []); setReadIds(new Set((reads.data || []).map(item => item.announcement_id))) } setLoading(false) }, [user.id])
  useEffect(() => { load() }, [load])
  const unread = useMemo(() => notices.filter(item => !readIds.has(item.id)).length, [notices, readIds])
  async function markRead(ids) { const { error } = await supabase.from('announcement_reads').upsert(ids.map(announcement_id => ({ announcement_id, user_id: user.id, read_at: new Date().toISOString() })), { onConflict: 'announcement_id,user_id' }); if (error) setError(workflowError(error)); else setReadIds(current => new Set([...current, ...ids])) }
  return <section className="notification-center"><header className="workflow-heading"><div><p className="eyebrow">School communications</p><h1>Notifications</h1><p className="progress-report-note">{unread ? `${unread} unread school notice${unread === 1 ? '' : 's'}.` : 'You are up to date.'}</p></div>{unread > 0 && <button onClick={() => markRead(notices.filter(item => !readIds.has(item.id)).map(item => item.id))}>Mark all read</button>}</header>{error && <p className="workflow-error" role="alert">{error}</p>}{loading ? <p role="status">Loading notifications…</p> : <section className="workflow-panel notification-list">{notices.map(notice => <article className={readIds.has(notice.id) ? 'read' : 'unread'} key={notice.id}><div><strong>{notice.title}</strong><small>{notice.published_at ? new Date(notice.published_at).toLocaleDateString('en-ZW') : 'School notice'}</small><p>{notice.body}</p></div>{!readIds.has(notice.id) && <button onClick={() => markRead([notice.id])}>Mark read</button>}</article>)}{!notices.length && <p className="portal-empty-copy">No notices are available yet.</p>}</section>}</section>
}
