import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function OfficialReports() {
  const [reports, setReports] = useState([]), [selected, setSelected] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const load = useCallback(async () => {
    setLoading(true)
    const { data, error: loadError } = await supabase.from('report_release_snapshots').select('id,academic_year,academic_term,assessments,average_percent,overall_grade,class_rank,class_size,released_at,publication:report_publications!report_release_snapshots_publication_id_fkey(campus:campuses(name))').order('released_at', { ascending: false })
    if (loadError) setError(workflowError(loadError)); else { setReports(data || []); setSelected(data?.[0] || null) }
    setLoading(false)
  }, [])
  useEffect(() => { load() }, [load])
  return <section><header className="workflow-heading"><div><p className="eyebrow">Academic progress</p><h1>Official reports</h1><p className="progress-report-note">These are the frozen assessment results from each formally released report period.</p></div>{selected && <button className="primary-action" onClick={() => window.print()}>Print official report</button>}</header>{error && <p className="workflow-error" role="alert">{error}</p>}{loading ? <p role="status">Loading official reports…</p> : reports.length ? <div className="official-report-layout"><aside className="workflow-panel official-report-list">{reports.map(item => <button className={selected?.id === item.id ? 'active' : ''} key={item.id} onClick={() => setSelected(item)}><strong>{item.academic_year} · {item.academic_term}</strong><small>{item.publication?.campus?.name || 'Fordridge Schools'}</small><small>Released {new Date(item.released_at).toLocaleDateString()}</small></button>)}</aside><article className="progress-report-sheet official-report-sheet"><div className="progress-report-heading"><div><p className="eyebrow">Fordridge Schools</p><h2>Official academic report</h2><p>{selected?.academic_year} · {selected?.academic_term}</p></div><div><strong>Released report</strong><small>{selected && new Date(selected.released_at).toLocaleString()}</small></div></div><section className="report-summary"><article><span>Average</span><strong>{selected?.average_percent ?? '—'}%</strong><small>At time of release</small></article><article><span>Overall grade</span><strong>{selected?.overall_grade || '—'}</strong><small>At time of release</small></article><article><span>Class position</span><strong>{selected?.class_rank ? `${selected.class_rank} / ${selected.class_size}` : '—'}</strong><small>Position / class size</small></article></section><table className="workflow-table"><thead><tr><th>Subject / assessment</th><th>Date</th><th>Mark</th><th>Percentage</th></tr></thead><tbody>{(selected?.assessments || []).map((item, index) => <tr key={`${item.title}-${index}`}><td>{item.title}</td><td>{item.event_date}</td><td>{item.score} / {item.max_score}</td><td>{Math.round(Number(item.score) / Number(item.max_score) * 100)}%</td></tr>)}</tbody></table></article></div> : <section className="workflow-panel"><p className="portal-empty-copy">No official report has been released for you yet.</p></section>}</section>
}
