import { useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function ReportVerification() {
  const [hash, setHash] = useState(''), [result, setResult] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false)
  async function verify(event) { event.preventDefault(); setLoading(true); setError(''); setResult(null); const { data, error: queryError } = await supabase.from('report_release_snapshots').select('academic_year,academic_term,released_at,publication:report_publications!report_release_snapshots_publication_id_fkey(campus:campuses(name))').eq('integrity_hash', hash.trim()).maybeSingle(); if (queryError) setError(workflowError(queryError)); else setResult(data); setLoading(false) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Formal reports</p><h1>Report verification</h1><p className="progress-report-note">Verify a released report integrity fingerprint without displaying learner assessment data.</p></div></header>{error && <p className="workflow-error" role="alert">{error}</p>}<form className="workflow-panel workflow-form" onSubmit={verify}><label className="workflow-wide">Integrity hash<input required value={hash} onChange={event => setHash(event.target.value)} placeholder="Paste the report fingerprint" /></label><div className="workflow-actions workflow-wide"><button className="primary-action" disabled={loading}>{loading ? 'Verifying…' : 'Verify report'}</button></div></form>{result === null && hash && !loading && <p className="portal-empty-copy">No released report matches that fingerprint.</p>}{result && <section className="workflow-panel report-verification-result"><span>Verified release</span><h2>{result.publication?.campus?.name || 'Fordridge Schools'} · {result.academic_year} · {result.academic_term}</h2><p>Released {new Date(result.released_at).toLocaleString()}</p></section>}</section>
}
