import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { workflowError } from './workflow'

export default function ReportSettings() {
  const [campuses, setCampuses] = useState([]), [settings, setSettings] = useState([]), [draft, setDraft] = useState({ campus_id: '', academic_year: String(new Date().getFullYear()), academic_term: 'Term 1', next_term_begins_on: '', class_teacher_name: '', head_of_school_name: '' }), [error, setError] = useState(''), [notice, setNotice] = useState(''), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { const [schools, reportSettings] = await Promise.all([supabase.from('campuses').select('id,name').order('name'), supabase.from('report_term_settings').select('*,campus:campuses(name)').order('academic_year', { ascending: false })]); const failed = [schools, reportSettings].find(item => item.error); if (failed) setError(workflowError(failed.error)); else { setCampuses(schools.data || []); setSettings(reportSettings.data || []); setDraft(current => ({ ...current, campus_id: current.campus_id || schools.data?.[0]?.id || '' })) } }, [])
  useEffect(() => { load() }, [load])
  async function save(event) { event.preventDefault(); setSaving(true); setError(''); const { error } = await supabase.from('report_term_settings').upsert({ ...draft, academic_year: Number(draft.academic_year), next_term_begins_on: draft.next_term_begins_on || null, class_teacher_name: draft.class_teacher_name.trim() || null, head_of_school_name: draft.head_of_school_name.trim() || null, updated_by: (await supabase.auth.getUser()).data.user?.id }, { onConflict: 'campus_id,academic_year,academic_term' }); if (error) setError(workflowError(error)); else { setNotice('Report settings saved.'); await load() } setSaving(false) }
  return <section><header className="workflow-heading"><div><p className="eyebrow">Formal reports</p><h1>Report settings</h1><p className="progress-report-note">Set the typed approval names and next-term date used on published reports.</p></div></header>{error && <p className="workflow-error" role="alert">{error}</p>}{notice && <p className="workflow-notice" role="status">{notice}</p>}<form className="workflow-panel workflow-form" onSubmit={save}><label>Campus<select required value={draft.campus_id} onChange={e => setDraft({ ...draft, campus_id: e.target.value })}>{campuses.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Academic year<input type="number" min="2000" required value={draft.academic_year} onChange={e => setDraft({ ...draft, academic_year: e.target.value })} /></label><label>Term<select value={draft.academic_term} onChange={e => setDraft({ ...draft, academic_term: e.target.value })}>{['Term 1','Term 2','Term 3'].map(item => <option key={item}>{item}</option>)}</select></label><label>Next term begins<input type="date" value={draft.next_term_begins_on} onChange={e => setDraft({ ...draft, next_term_begins_on: e.target.value })} /></label><label>Class teacher approval name<input value={draft.class_teacher_name} onChange={e => setDraft({ ...draft, class_teacher_name: e.target.value })} placeholder="[EDIT THIS]" /></label><label>Head of school approval name<input value={draft.head_of_school_name} onChange={e => setDraft({ ...draft, head_of_school_name: e.target.value })} placeholder="[EDIT THIS]" /></label><div className="workflow-actions workflow-wide"><button className="primary-action" disabled={saving}>{saving ? 'Saving…' : 'Save report settings'}</button></div></form><section className="workflow-panel"><h2>Configured report periods</h2>{settings.map(item => <p key={item.id}><strong>{item.campus?.name || 'All campuses'} · {item.academic_year} · {item.academic_term}</strong><br />Class teacher: {item.class_teacher_name || '[EDIT THIS]'} · Head of school: {item.head_of_school_name || '[EDIT THIS]'}</p>)}{!settings.length && <p className="portal-empty-copy">No report settings have been configured yet.</p>}</section></section>
}
