-- Extends Fordridge's existing fee_records model; it does not create a second learner table.
alter table public.fee_records add column if not exists paid_amount numeric(12,2) not null default 0 check (paid_amount >= 0), add column if not exists payment_reference text, add column if not exists updated_at timestamptz not null default now();
alter table public.fee_records add constraint fee_records_paid_amount_not_over_due check (paid_amount <= amount);
create table public.fee_transactions (id uuid primary key default gen_random_uuid(), fee_record_id uuid not null references public.fee_records(id) on delete cascade, campus_id uuid not null references public.campuses(id), amount numeric(12,2) not null check (amount > 0), payment_method text not null check (payment_method in ('bank_transfer','cash','card','mobile_money')), reference text, recorded_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.audit_trail (id uuid primary key default gen_random_uuid(), campus_id uuid references public.campuses(id), actor_id uuid references public.profiles(id), entity_type text not null, entity_id uuid not null, action text not null, detail jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
alter table public.fee_transactions enable row level security; alter table public.audit_trail enable row level security;
create policy "fee transactions scoped read" on public.fee_transactions for select using (public.my_role() = 'admin' or exists (select 1 from public.fee_records r where r.id = fee_record_id and (r.student_id = auth.uid() or exists (select 1 from public.student_guardians g where g.student_id = r.student_id and g.parent_id = auth.uid()))));
create policy "admins record fee transactions" on public.fee_transactions for insert with check (public.my_role() = 'admin' and recorded_by = auth.uid());
create policy "admins read audit trail" on public.audit_trail for select using (public.my_role() = 'admin');
create policy "admins write audit trail" on public.audit_trail for insert with check (public.my_role() = 'admin' and actor_id = auth.uid());
create or replace function public.log_fee_transaction() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.audit_trail(campus_id, actor_id, entity_type, entity_id, action, detail) values (new.campus_id, new.recorded_by, 'fee_transaction', new.id, 'created', jsonb_build_object('fee_record_id', new.fee_record_id, 'amount', new.amount, 'method', new.payment_method)); return new; end; $$;
create trigger fee_transaction_audit after insert on public.fee_transactions for each row execute function public.log_fee_transaction();
