-- Public website enquiry storage. Authenticated staff should receive a separate
-- policy for reading enquiries through the portal when that feature is added.
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  email text not null check (char_length(trim(email)) > 0),
  phone text,
  message text not null check (char_length(trim(message)) > 0),
  enquiry_type text not null default 'enquiry',
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

create policy "Public can submit enquiries"
on public.enquiries
for insert
to anon, authenticated
with check (true);
