-- Fordridge portal schema: apply with `supabase db push` or in the Supabase SQL editor.
create type public.app_role as enum ('student','parent','teacher','admin');
create table public.campuses(id uuid primary key default gen_random_uuid(),code text unique not null check(code in('junior','senior')),name text unique not null,created_at timestamptz not null default now());
insert into public.campuses(code,name)values('junior','Fordridge Junior School'),('senior','Fordridge Senior School');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',role public.app_role not null default 'student',campus_id uuid references public.campuses(id),created_at timestamptz not null default now());
-- Public signup can only create students; admins assign campus and elevated roles.
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name,role)values(new.id,coalesce(new.raw_user_meta_data->>'full_name',''),'student');return new;end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table public.announcements(id uuid primary key default gen_random_uuid(),campus_id uuid references public.campuses(id) not null,title text not null,body text not null,published_at timestamptz,author_id uuid references public.profiles(id),created_at timestamptz not null default now());
create table public.fee_records(id uuid primary key default gen_random_uuid(),campus_id uuid references public.campuses(id) not null,student_id uuid references public.profiles(id) not null,amount numeric(12,2) not null check(amount>=0),currency text not null default 'USD',due_date date,status text not null default 'pending' check(status in('pending','paid','overdue')),created_at timestamptz not null default now());
create table public.student_guardians(student_id uuid references public.profiles(id) on delete cascade,parent_id uuid references public.profiles(id) on delete cascade,primary key(student_id,parent_id));
create table public.timetable(id uuid primary key default gen_random_uuid(),campus_id uuid references public.campuses(id) not null,audience_role public.app_role,subject text not null,day_of_week smallint not null check(day_of_week between 1 and 7),starts_at time not null,ends_at time not null,teacher_id uuid references public.profiles(id),created_at timestamptz not null default now(),check(ends_at>starts_at));
alter table public.profiles enable row level security;alter table public.campuses enable row level security;alter table public.announcements enable row level security;alter table public.fee_records enable row level security;alter table public.student_guardians enable row level security;alter table public.timetable enable row level security;
create function public.my_role() returns public.app_role language sql stable security definer set search_path=public as $$select role from public.profiles where id=auth.uid()$$;create function public.my_campus_id() returns uuid language sql stable security definer set search_path=public as $$select campus_id from public.profiles where id=auth.uid()$$;
create policy "profile own or admin" on public.profiles for select using(id=auth.uid() or public.my_role()='admin');create policy "admin profiles" on public.profiles for all using(public.my_role()='admin') with check(public.my_role()='admin');create policy "campuses authenticated read" on public.campuses for select to authenticated using(true);
create policy "announcements campus read" on public.announcements for select using(campus_id=public.my_campus_id() or public.my_role()='admin');create policy "announcements staff manage" on public.announcements for all using(public.my_role()in('teacher','admin')and(campus_id=public.my_campus_id()or public.my_role()='admin'))with check(public.my_role()in('teacher','admin')and(campus_id=public.my_campus_id()or public.my_role()='admin'));
create policy "timetable campus read" on public.timetable for select using(campus_id=public.my_campus_id()or public.my_role()='admin');create policy "timetable staff manage" on public.timetable for all using(public.my_role()in('teacher','admin')and(campus_id=public.my_campus_id()or public.my_role()='admin'))with check(public.my_role()in('teacher','admin')and(campus_id=public.my_campus_id()or public.my_role()='admin'));
create policy "guardian links scoped read" on public.student_guardians for select using(parent_id=auth.uid()or student_id=auth.uid()or public.my_role()='admin');create policy "guardian links admin manage" on public.student_guardians for all using(public.my_role()='admin')with check(public.my_role()='admin');
create policy "fees scoped read" on public.fee_records for select using(public.my_role()='admin'or(public.my_role()='student'and student_id=auth.uid())or exists(select 1 from public.student_guardians g where g.student_id=fee_records.student_id and g.parent_id=auth.uid()));create policy "fees admin manage" on public.fee_records for all using(public.my_role()='admin')with check(public.my_role()='admin');
